version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: docker-sqlserver-integration
    environment:
      SA_PASSWORD: MeuDb@123
      ACCEPT_EULA: Y
    ports:
      - "11533:1433"
    volumes:
      - ./backup:/var/opt/mssql/backup  
      - ./log:/var/opt/mssql/log  
      - ./data:/var/opt/mssql/data  

volumes:
  ssis-packages:

 